name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    type: published

env:
  BuildVersion: "CI.${{ github.run_id }}"
  BuildBranch: "${{ github.ref }}"
  BuildParameters: "/v:Minimal /p:Configuration=Release Eto.Parse.sln"

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: dotnet build ${{ env.BuildParameters }}

      - name: Pack
        run: dotnet pack ${{ env.BuildParameters }}

      - name: Test
        run: dotnet test --no-build --filter TestCategory!=not-working ${{ env.BuildParameters }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: artifacts/nuget/**/*.nupkg

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Download NuGet Packages
        uses: actions/download-artifact@v4.1.7
        with:
          name: nuget

      - name: Push packages
        run: dotnet nuget push './nuget/**/*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
